title: Human-Centered AI
author: Ronit Kathuria
email: ronitkats15@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
At HCAI, we focus on innovations centered on the use of deep learning to transform
the manner in which humans interact with technology and even each other.
theme: minima 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ronitkathuria15 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
